"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.Store = exports.Dom = exports.Component = void 0;
var compile_1 = require("./compile");
Object.defineProperty(exports, "Component", { enumerable: true, get: function () { return compile_1.Component; } });
var Dom_1 = require("./Dom");
exports.Dom = Dom_1.default;
var store_1 = require("./store");
var Store = new store_1.default('user');
exports.Store = Store;
exports.default = compile_1.default;
window.Cpage = new compile_1.default();
